apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: systems.cube.femtoframework.org # Obligatory field to identify the resource
spec:
  group: cube # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v7
      served: true
      storage: true
  scope: namespaced
  names: # Obligatory field to identify the resource
    plural: systems
    singular: system
    kind: System
    shortNames:
      - sys
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            labels:
              type: object
              properties:
                access:
                  type: string
              additionalProperties:
                type: object
            annotations:
              type: object
        spec:
          type: object
          properties:
            class:
              type: string
          additionalProperties:
            type: object

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appservers.cube.femtoframework.org # Obligatory field to identify the resource
spec:
  group: cube # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v7
      served: true
      storage: true
  scope: namespaced
  names: # Obligatory field to identify the resource
    plural: appservers
    singular: appserver
    kind: AppServer
    shortNames:
      - as
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            labels:
              type: object
              properties:
                access:
                  type: string
              additionalProperties:
                type: object
            annotations:
              type: object
        spec:
          type: object
          properties:
            class:
              type: string
          additionalProperties:
            type: object


---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tcpendpoints.cube.femtoframework.org # Obligatory field to identify the resource
spec:
  group: cube # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v7
      served: true
      storage: true
  scope: namespaced
  names: # Obligatory field to identify the resource
    plural: tcpendpoints
    singular: tcpendpoint
    kind: TcpEndpoint
    shortNames:
      - te
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            labels:
              type: object
              properties:
                access:
                  type: string
              additionalProperties:
                type: object
            annotations:
              type: object
        spec:
          type: object
          properties:
            class:
              type: string
            executor:
              type: object
              properties:
                class:
                  type: string
                name:
                  type: string
                maxThreads:
                  type: integer
                minSpareThreads:
                  type: integer
                maxSpareThreads:
                  type: integer
                incThreads:
                  type: integer
              additionalProperties:
                type: object
          additionalProperties:
            type: object
