apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apsisservers.apsis.femtoframework.org # Obligatory field to identify the resource
spec:
  group: apsis # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v7
      served: true
      storage: true
  scope: namespaced
  names: # Obligatory field to identify the resource
    plural: apsisservers
    singular: apsisserver
    kind: ApsisServer
    shortNames:
      - aps
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            labels:
              type: object
              properties:
                access:
                  type: string
              additionalProperties:
                type: object
            annotations:
              type: object
        spec:
          type: object
          properties:
            class:
              type: string
          additionalProperties:
            type: object

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rmiservers.cube.femtoframework.org # Obligatory field to identify the resource
spec:
  group: apsis # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v7
      served: true
      storage: true
  scope: namespaced
  names: # Obligatory field to identify the resource
    plural: rmiservers
    singular: rmiserver
    kind: RmiServer
    shortNames:
      - rmi
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            labels:
              type: object
              properties:
                access:
                  type: string
              additionalProperties:
                type: object
            annotations:
              type: object
        spec:
          type: object
          properties:
            class:
              type: string
          additionalProperties:
            type: object

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventservers.cube.femtoframework.org # Obligatory field to identify the resource
spec:
  group: apsis # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v7
      served: true
      storage: true
  scope: namespaced
  names: # Obligatory field to identify the resource
    plural: eventservers
    singular: eventserver
    kind: EventServer
    shortNames:
      - es
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            labels:
              type: object
              properties:
                access:
                  type: string
              additionalProperties:
                type: object
            annotations:
              type: object
        spec:
          type: object
          properties:
            class:
              type: string
          additionalProperties:
            type: object

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gmppconnectors.cube.femtoframework.org # Obligatory field to identify the resource
spec:
  group: apsis # Obligatory field to identify the resource
  versions: # Obligatory field to identify the resource
    - name: v7
      served: true
      storage: true
  scope: namespaced
  names: # Obligatory field to identify the resource
    plural: gmppconnectors
    singular: gmppconnector
    kind: GmppConnector
    shortNames:
      - gmpp
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            labels:
              type: object
              properties:
                access:
                  type: string
              additionalProperties:
                type: object
            annotations:
              type: object
        spec:
          type: object
          properties:
            daemon:
              type: boolean
            supportVersions:
              type: string
            suportCodecs:
              type: string
          additionalProperties:
            type: object
